# Generated by Django 3.2.21 on 2023-09-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../samples/default_profile_lompwn', upload_to='images/'),
        ),
    ]
